/**
 * Generated by openapi-typescript from ../openapi.yaml
 * DO NOT EDIT BY HAND. Re-run `npm run api:types` (or `/openapi-sync`) to regenerate.
 */

export interface paths {
  "/users": {
    get: operations["listUsers"];
    post: operations["createUser"];
  };
  "/users/{id}": {
    get: operations["getUser"];
    delete: operations["deleteUser"];
  };
}

export interface components {
  schemas: {
    User: {
      id: string;
      email: string;
      name?: string;
      createdAt: string;
    };
    CreateUserInput: {
      email: string;
      name?: string;
    };
  };
}

export interface operations {
  listUsers: {
    responses: {
      200: { content: { "application/json": components["schemas"]["User"][] } };
    };
  };
  createUser: {
    requestBody: { content: { "application/json": components["schemas"]["CreateUserInput"] } };
    responses: {
      201: { content: { "application/json": components["schemas"]["User"] } };
    };
  };
  getUser: {
    parameters: { path: { id: string } };
    responses: {
      200: { content: { "application/json": components["schemas"]["User"] } };
      404: { content: never };
    };
  };
  deleteUser: {
    parameters: { path: { id: string } };
    responses: {
      204: { content: never };
    };
  };
}
